#!/usr/bin/env python3
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
H=Path('/mnt/c/programmieren/mergeworkcbeta/cbeta-translator/runs/CLAUDE-RUNS/RUN-20260711-1248-full-cbeta-translation/dictionary-build')
R={
't_8bd3edf4e467':('PASS','The current entry treats wall-facing for nine years as the Bodhidharma case action and explicitly limits it against a sitting manual. No extant prose asserts that a physical object is made from a material; the prior material-claim trigger is cleared rather than merely excused. The opening retains both the action and duration, and opposed appraisals are visible.', [('X/X68/X68n1318.xml','0382c11','0382c19','Bodhidharma faces the wall for nine years without speaking, paired with Huike standing in snow and severing his arm.'),('X/X82/X82n1571.xml','0044b20','0044c04','Sansheng Jichang calls the nine years cold sitting in vain, anchoring the limiting appraisal.')]),
't_f050bdd79dfe':('PASS','The value inference is case-bound, not free symbolism. The questioner presents uncut jade for decision or carving, explicitly invokes Bian He, and the respondents refuse the flattering setup. “Valuable but unfinished material” is therefore an observable self-presentation whose failure is stated, while the preferred target keeps the rough-jade object visible.', [('X/X66/X66n1297.xml','0343c07','0343c14','The Baizhang exchange asks for a decision on the carried uncut jade and ends in rebuke and a blow.'),('T/T51/T51n2076.xml','0319c03','0319c04','The Touzi form requests carving and explicitly raises Bian He, while Touzi refuses the proposed material/appraiser relation.')]),
't_8412042c8a80':('PASS','The revised opening begins with an English interpretation rather than a bare quotation and correctly identifies the phrase as the before-side of Yunmen’s paired prompt. Later witnesses recut before, after, and the exact fifteenth; the entry explicitly rejects an unanchored equation with “before awakening.”', [('X/X67/X67n1307.xml','0492c01','0492c08','Yunmen’s raised case states before the fifteenth and demands a phrase for after it.'),('J/J38/J38nB407.xml','0215a30','0215b07','Qianshan distinguishes before, after, and exactly the fifteenth, anchoring the three-position recut.')]),
't_38cc4291fe2a':('PASS','The opening describes the imperative within the Bodhidharma–Huike exchange and separately notes Miyun’s direct reuse. It does not treat mind as a producible object or generalize the demand into an instruction to display thoughts. Repetition across quoted transmissions is disclosed as case transmission, not mistaken for independent events.', [('J/J34/J34nB299.xml','0163c24','0163c25','Bodhidharma demands the mind and Huike answers that it cannot be found.'),('J/J10/J10nA158.xml','0035c01','0035c02','Miyun directly reuses the imperative with his own student, supporting deployment beyond quotation.')]),
't_8e0e666cb806':('REVISE','The underlying one-meal decision is supported, but the current Explanation is reader-visibly corrupted: after two sound sentences it inserts the lowercase fragment “one inherited case-meal,” runs multiple control findings together without punctuation, and substantially repeats the Note. Rewrite it as continuous entry-specific prose; retain Jinniu as the case-master modifier, the rice as the food, and the distinct companion provisions.', [('X/X82/X82n1571.xml','0250b06','0250b07','Wei’an pairs Yunmen’s cake with Jinniu’s rice as provisions.'),('J/J33/J33nB294.xml','0732a20','0732a22','Liangting says Caoxi water is cooked into Jinniu’s rice, anchoring the meal object without making Jinniu a material adjective.')]),
't_227099445b8c':('REVISE','The added Zongmi contrast is a useful anchor, but the current Explanation is corrupted and internally stale: unpunctuated control fragments interrupt the prose, “The three witnesses” remains after a fourth witness was added, and the text first says the contrast is unanchored before saying it is now anchored. Rewrite around two bounded deployments: looser comprehension/realization uses and Zongmi’s explicit understanding-realization versus verification-realization contrast.', [('T/T48/T48n2015.xml','0407c18','0407c19','Zongmi explicitly assigns sudden understanding followed by gradual cultivation to understanding-realization, anchoring the contrast.'),('J/J25/J25nB163.xml','0238a05','0238a05','Guting warns against making a view of understanding-realization and adaptability, anchoring the critical deployment.')]),
't_cbbfa37e2710':('PASS','The hall is an institutional case-locale, not a generic wooden building or a claim that the hall is physically made from dead wood. Xiangtian’s historical clause explicitly says Shishuang established the Dead-Tree Hall and housed the dead-tree assembly; later questions and verses use that named locale. The modifier is preserved in display and bounded to this inherited hall.', [('J/J27/J27nB191.xml','0161b16','0161b17','The record explicitly states that Shishuang established the Dead-Tree Hall and settled the dead-tree assembly there.'),('X/X78/X78n1556.xml','0659c23','0659c24','A direct question asks about the matter before the Dead-Tree Hall, confirming its reusable case-locale status.')]),
}
rows=[]
for i,(decision,reason,anchors) in R.items():
 p=H/'fresh-build/entries'/i/'entry.v2.json';w=H/'fresh-build/entries'/i/'WORK.md';d=json.load(open(p))
 rows.append({'id':i,'term':d['SourceTerm'],'decision':decision,'entrySha256':hashlib.sha256(p.read_bytes()).hexdigest(),'workSha256':hashlib.sha256(w.read_bytes()).hexdigest(),'reason':reason,'anchors':[{'RelPath':a,'FromLb':b,'ToLb':c,'finding':f} for a,b,c,f in anchors]})
out={'schemaVersion':'current-byte-semantic-cross-review.v1','generatedUtc':datetime.now(timezone.utc).isoformat(),'reviewer':'Codex read-only cross-review of A-authored feedback repairs','scopeIds':list(R),'readOnly':True,'summary':{'PASS':sum(x['decision']=='PASS' for x in rows),'REVISE':sum(x['decision']=='REVISE' for x in rows),'REJECT':sum(x['decision']=='REJECT' for x in rows)},'rows':rows}
(H/'maintenance/current-byte-crossreview-a-feedback-repairs-7.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
