#!/usr/bin/env python3
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
H=Path('/mnt/c/programmieren/mergeworkcbeta/cbeta-translator/runs/CLAUDE-RUNS/RUN-20260711-1248-full-cbeta-translation/dictionary-build')
R={
't_1910ed86a5c7':('REVISE','The one Guang’e knife-dropping case and its conflicting appraisals are accurately bounded, and Jin Zhengxi is correctly restored as the exact questioner in Juelang’s record. However, occurrence 3 structurally links the respondent as roster-canonical Baichi Xingyuan while its note and Explanation call him Baichi Yuanshuo. Those are aliases of one roster node, but reader-visible prose must use names[0] consistently.','Dahui’s two clauses narrate the same inherited action under different arguments; Hanxiu, Jin Zhengxi/Juelang, and Chushi explicitly question or criticize what follows from it. J28nB202’s title and roster resolve 百癡元 to Baichi Xingyuan, exposing the prose/link mismatch.'),
't_05b3ddb5f92c':('PASS','The preferred target “command of language” fits praise, testing, imagined free use, and explicit criticism without equating verbal skill with realization. Xuansha owns the quoted deaf-person question in Dahui’s record; Dahui is correctly retained as later quoter/commentator. All six occurrence paths represent distinct works and the prose states the limiting Ying’an counterexample.','M59 praises verbal command only as near the Way; T47 and X83 assign the deaf-person test to Xuansha; Zhongfeng, Qianyan, and Ying’an supply free-use, testing, and misdirected-effort predicates.'),
't_e6077ed1bb67':('PASS','The entry correctly treats 別語 as an alternative response within encounter rhetoric and does not reduce it to editorial variation. Direct unnamed requesters, the Touzi-directed request, Huanyou’s embedded teacher speech, the anonymous appraisal verse, and Xiatang’s own further saying have distinct grammatical frames and are accurately separated. No unsupported independent-work count appears in the prose.','The early T51/B14 parallels openly say 請別語; D48 asks Touzi not to answer by substitution; J10’s explicit teacher-introduction governs Huanyou’s 更無別語; C078 and X69 preserve verse deployments with the correct surface actors.'),
't_50ebbb091a86':('REVISE','The Yongjia work sense is sound for the explicitly titled and attributed witnesses, and the Pu’an work is properly excluded. The sixth witness is not correctly attributed: J28nB219 is the Recorded Sayings of Zhuanyu Guanheng, and the occurrence lies in a signed/reprinted preface, not anonymous source-compiler narration. Its note also mislabels the source as “Collected Works of Gushan Zhiqi.” In addition, the X82 awakening notice merely says a neighbor recited 證道歌 in the retained span; calling all six witnesses independently Yongjia-specific requires either fuller identity proof for that notice or a narrower claim.','T51 explicitly says Yongjia composed one song; X66 says 永嘉證道歌; J28’s reprint preface explicitly names True Awakening Master and the work, but its exact author must be resolved from the preface rather than the book owner. X82’s stored clause lacks an explicit Yongjia identifier.'),
't_da2c4e4b0c84':('PASS','The revision correctly restores context-dependent appraisal. Five witnesses criticize limited sitting, guarded stillness, speechless withdrawal, or an adopted self-name; Xutang’s memorial verse instead uses the label in wall-facing imagery. Shiyu Mingfang is correctly bound as the authored answer. The prose therefore avoids the former uniform negative definition while keeping one lexical label.','Poshan, Shiyu, Wanshou, and Guangshou supply explicit negative complements; Wuzhun reports and mocks Cheng’s self-name; Xutang contrasts public courts with 枯禪面壁 without the same diagnostic syntax.'),
't_410c5d822ad1':('REVISE','The semantic account—borrowed look-alike phrases used as proof of understanding—is well supported across six distinct works. Actor fields now name Yunju Daoying and Deshan Xuanjian correctly, but occurrences 5 and 6 retain contradictory reader prose saying first that an unnamed speaker/elder is exact and then that full-case ownership identifies the named master. The requested recursive-boilerplate repair is therefore incomplete and must be reduced to one unambiguous actor statement per note.','Zhongfeng’s two authored texts, Foyan, Yunwai, Yunju, and Deshan all criticize seeking, storing, or testing with resembling language. X64’s section and X83’s explicit Deshan heading support the named actors; the residual unnamed clauses contradict those decisions.'),
't_28c4ca8397ca':('PASS','The sword image is bounded by explicit comparison, identification, wielding, and severing predicates and does not become a manufactured/material weapon claim. Linji owns the original four-shout comparison. Dahui’s occurrence correctly makes Dahui the surface utterer and later quoter/commentator while retaining Linji only as person discussed. The six paths are independent works and the prose accurately describes their different deployments.','Linji compares one shout to the sword; Zhenjing and Yuanwu classify it; Dahui identifies Linji’s presentation; Ying’an wields it; the linked-lamps address explicitly uses it to sever doubt.')}
rows=[]
for i,(disp,reason,evidence) in R.items():
 p=H/'fresh-build/entries'/i/'entry.v2.json';d=json.load(open(p))
 rows.append({'id':i,'sourceTerm':d['SourceTerm'],'reviewedCurrentEntrySha256':hashlib.sha256(p.read_bytes()).hexdigest(),'disposition':disp,'independentQualified':True,'reason':reason,'evidence':[evidence,'All stored KWIC paths, line bounds, current actor fields, source titles/headings, Explanation, and WORK ledger were reviewed on the current bytes.']})
out={'schemaVersion':'current-byte-sensitive7-independent-review.v1','generatedUtc':datetime.now(timezone.utc).isoformat(),'entriesEdited':False,'summary':{'PASS':sum(r['disposition']=='PASS' for r in rows),'REVISE':sum(r['disposition']=='REVISE' for r in rows)},'rows':rows}
(H/'maintenance/current-byte-sensitive7-independent-review.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
