#!/usr/bin/env python3
import json
from pathlib import Path
H=Path('/mnt/c/programmieren/mergeworkcbeta/cbeta-translator/runs/CLAUDE-RUNS/RUN-20260711-1248-full-cbeta-translation/dictionary-build')
D={
't_4fd4cdbc25b0':('The witnesses support “discriminating mind” as ordinary differentiating judgment, not a named faculty.','Interview rebukes, instructions, and the ancient-record discourse all oppose or suspend discriminating judgment.','Checked neutral uses and the contrast with “undiscriminating mind”; no second referent emerged.','The ancient-record passage supplies an explicit contrary term and limits the article to the contrast actually stated.','discriminating mind; differentiating mind'),
't_6b69c60b142d':('Two grammatical senses are retained: “whole function” as a noun phrase and “use entirely” as an adverbial construction.','Body/function discussions use 全用 nominally; strength, intention, and fasting-of-mind passages use 全 adverbially with 用.','Tested whether all cases could be collapsed into “complete use”; syntax and objects falsify that collapse.','The calligraphy and exertion witnesses are ordinary adverbial uses and prevent a technical-only account.','whole function; use entirely; apply all one’s strength'),
't_7c065becc98f':('The reversed pair means living together and dying together across memorial, verse, and appraisal settings.','The complete cases retain the same paired predicates while evaluations differ.','Checked whether the wording names a rank, vow, or rite; no retained witness does.','One address refuses to accept the pair as a merely verbal conclusion, limiting any uniformly positive reading.','live together and die together; share life and death'),
't_7ee5a99b989c':('The phrase is the named “Deva school” question in the Baling case and its later raisings.','Baling’s answer and Yuanwu’s warning against a historical-sect reading anchor the case-specific use.','Compared literal school-history readings with the full commentary; the commentary explicitly rejects that route.','The entry does not identify a general externalist institution beyond the raised case formula.','Deva school; Baling Deva school'),
't_8873b46d7a4e':('The coordinated action means taking up the mallet and raising the whisk in formal teaching speech.','Hall addresses treat both objects as paired public actions, sometimes questioning their adequacy.','Checked isolated mallet and whisk mentions; they do not establish the full coordinated phrase.','Critical witnesses deny that performing the pair alone settles the matter, limiting ceremonial overreading.','take up the mallet and raise the whisk; mallet and whisk'),
't_88b6f3526f8e':('The phrase denotes transmitting or conferring precepts, with the recipient and occasion supplied locally.','Biographical and institutional notices name teachers who confer precepts and disciples who receive them.','Checked whether it means lineage transmission generally; retained clauses specifically govern precepts.','Ordination notices keep the act institutional and do not make it synonymous with every teaching handover.','transmit the precepts; confer precepts'),
't_8e59a2d1c6b2':('The compound names an iron caltrop; “iron” remains a material modifier in every retained image.','Speakers offer, swallow, tread on, or drive the hard pointed object through eyes; none deletes the iron wording.','Compared generic caltrop and metaphor-only readings; the exact compound consistently preserves the hard iron object.','The predicates vary, so the article reports the object and its handling without assigning one fixed symbolic value.','iron caltrop; iron burr'),
't_9db05c37d46c':('The opening identifies an exact inherited verse line and its later quotation history, not a free-standing botanical assertion.','Huineng’s verse frame and later appraisals repeatedly preserve the same full line.','Checked clipped bodhi/tree occurrences and later paraphrases; only exact-line witnesses support this entry.','Later speakers appraise the line differently, so quotation continuity does not imply one evaluation.','Bodhi originally has no tree; Huineng verse line'),
't_cb2186c9f436':('The compound denotes “wooden-plaque soup,” preserving 木 as the material of the plaque in the recorded rebuke.','The full cases pair an inedible wooden plaque with soup language as one concrete, deliberately impossible dish name.','Checked whether 木 modifies the soup directly or names a separate utensil; clause structure binds it to 札.','The image is retained literally; the witnesses do not authorize a fixed symbolic decoding of wood or soup.','wooden-plaque soup; wood tally soup'),
't_f634c481210b':('The verb-object phrase means to take in or incur a defeat or exposed flaw.','Case comments use it when an answer, maneuver, or appraisal leaves a failure showing.','Checked simple “accept” and architectural “gap” readings; encounter syntax supports failure/flaw.','Some clauses diagnose another speaker rather than self-confession, limiting the English subject supplied by context.','incur a defeat; take in a flaw'),
't_2ca177fa2e93':('The phrase is a direct negative command or description: do not deliberate.','Instructions and case quotations contrast it with pursuing calculations or discursive weighing.','Checked whether it independently names a meditation method; retained wording supplies negation, not a procedural program.','Context decides whether the phrase is imperative or descriptive; the entry preserves both grammars.','do not deliberate; without deliberation'),
't_c214ce1e79ca':('The verb-object phrase means to accord with principle or fit the stated rationale.','Questions, appraisals, and prose judgments test whether words or conduct fit the governing reason.','Checked agreement between people and contractual senses; the retained objects and predicates concern fit with 理.','The corpus also records failure to accord, so the phrase is not itself praise in every clause.','accord with principle; fit the rationale'),
't_ab761860367a':('The paired phrase names dying while seated or dying while standing.','Biographical and polemical passages coordinate the two bodily postures as reported death feats.','Checked whether 坐脫 alone should absorb the standing member; exact witnesses explicitly preserve both.','Some speakers question the value of such deaths, preventing the article from treating them as automatic proof of attainment.','die seated or standing; seated release and standing death'),
't_bca3ba8ebdb5':('The coordinated verbs mean to look back and inspect or attend carefully.','Addresses direct hearers to turn attention back, while narrative clauses describe looking and examining.','Checked mirror as a noun and institutional inspection senses; exact syntax keeps two verbal actions.','Objects and subjects vary, so the entry does not impose one inward or contemplative technique.','look back and inspect; turn and examine'),
't_bea7c499e294':('The term names an overnight lodging or the monk using such transient lodging, as local syntax decides.','Travel and monastery records place arrivals in a one-night stopping context and sometimes use the term for the lodger.','Checked dawn-only readings from the graphs; institutional contexts consistently concern temporary overnight stay.','Person and place uses remain distinct grammatical deployments of the same lodging term.','overnight lodging; transient lodger'),
't_4fcd5327b939':('The phrase means a token or object presented as proof of trust.','Transmission and gift narratives explicitly hand over an item to serve as evidence or token.','Checked generic expression-of-belief readings; concrete transfer verbs and objects require a token sense.','The particular object changes by case, so no single robe, document, or relic defines the phrase.','token of trust; proof token'),
}
for eid,(verdict,obs,fals,counter,probes) in D.items():
 p=H/'fresh-build/entries'/eid/'WORK.md'; old=p.read_text(encoding='utf8') if p.exists() else f'# Feedback ledger\n'
 old='\n'.join(x for x in old.splitlines() if not x.startswith(('feedback-inference-verdict:','feedback-observations:','feedback-falsification-searches:','feedback-counterexamples:','feedback-scope:','lookup-probes:','opening-interpretation-verdict:','modifier-relation-verdict:','display-modifier-verdict:')))
 block=f'''\nfeedback-inference-verdict: {verdict}\nfeedback-observations: {obs}\nfeedback-falsification-searches: {fals}\nfeedback-counterexamples: {counter}\nfeedback-scope: Exact headword witnesses in the frozen allowlist corpus and their complete cases.\nlookup-probes: {probes}.\nopening-interpretation-verdict: The opening is licensed by the retained full cases and bounded by the stated counterexample.\n'''
 if eid=='t_8e59a2d1c6b2':block+='modifier-relation-verdict: Iron modifies caltrop materially; it is not an optional intensifier.\ndisplay-modifier-verdict: The preferred target visibly retains “iron.”\n'
 if eid=='t_cb2186c9f436':block+='modifier-relation-verdict: Wood modifies plaque inside the compound, not soup directly.\ndisplay-modifier-verdict: The preferred target visibly retains the wooden plaque.\n'
 p.write_text(old.rstrip()+'\n'+block,encoding='utf8')
