// Services/StructuralSegmentParser.cs
//
// C# port of eng/tools/build-structural-segments.js (audit P3.1c, decision D5):
// collapses the third independent TEI parser into the app so segment maps can be
// generated without node. The port is BYTE-COMPATIBLE with the JS generator —
// identical segmentation state machine (same regex semantics via .NET Regex with the
// same patterns), identical JSONL output (same key order, same JS-style string
// escaping, LF line endings, source_sha256 header). Parity is pinned by golden-file
// tests (fixtures + goldens generated by the JS parser) and an env-gated full-corpus
// sweep (StructuralSegmentParserParityTests).
//
// When editing: change the JS and this file TOGETHER until the JS is retired
// (PR 3 of P3.1c), and keep the goldens regenerated from the JS.

using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace ReadZen.App.Services;

/// <summary>One extracted segment (mirrors the JS parser's internal shape).</summary>
public sealed record StructuralSegment(
    List<string> LbIds,
    string Text,
    string Type,
    string XmlId);

public static class StructuralSegmentParser
{
    // Same patterns as the JS parser; RegexOptions.IgnoreCase mirrors the /i flag.
    private static readonly Regex TagRe = new(@"<\/?[^>]+>", RegexOptions.Compiled);
    private static readonly Regex BodyRe = new(@"<body[^>]*>([\s\S]*?)<\/body>", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex LbEdRe = new("<lb\\b[^>]*\\bed=\"([^\"]+)\"", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex HeadOpenRe = new(@"<head[\s>]", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex HeadCloseRe = new(@"<\/head>", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex NoteAppOpenRe = new(@"^<(note|app)[\s>]", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex NoteAppCloseRe = new(@"^<\/(note|app)>", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex SelfClosingRe = new(@"\/>\s*$", RegexOptions.Compiled);
    private static readonly Regex ContainerOpenRe = new(@"^<(p|cell|item)[\s>]", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex ContainerCloseRe = new(@"^<\/(p|cell|item)>", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex LgOpenRe = new(@"^<lg[\s>]", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex LgCloseRe = new(@"^<\/lg>", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex LbRe = new(@"^<lb[\s]", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex NAttrRe = new("\\bn=\"([^\"]+)\"", RegexOptions.Compiled);
    private static readonly Regex EdAttrRe = new("\\bed=\"([^\"]+)\"", RegexOptions.Compiled);
    private static readonly Regex XmlIdAttrRe = new("xml:id=\"([^\"]+)\"", RegexOptions.Compiled);
    private static readonly Regex SkipOpenRe = new(@"^<(anchor|figure|rdg|lem|cb:mulu|cb:juan|cb:jhead|cb:tt|cb:coloph)", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex SkipCloseRe = new(@"^<\/(anchor|figure|rdg|lem|cb:mulu|cb:juan|cb:jhead|cb:tt|cb:coloph)", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex CaesuraRe = new(@"^<caesura", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex WsRunRe = new("[\\t\\n\\r ]+", RegexOptions.Compiled);
    private static readonly Regex DialogueMarkersRe = new("[云曰問答]", RegexOptions.Compiled);
    private static readonly Regex SpeakerMarkersRe = new("[師僧祖]", RegexOptions.Compiled);
    private static readonly Regex WumenRe = new("^無門曰", RegexOptions.Compiled);
    private static readonly Regex ShiSaysRe = new("^師[云曰]", RegexOptions.Compiled);

    private readonly record struct Token(bool IsTag, string Value);

    /// <summary>
    /// SHA-256 (lowercase hex) of the line-ending-normalized text. Same contract as
    /// the JS generator's sourceContentHash and SegmentMapService.TryComputeSourceHash.
    /// </summary>
    public static string SourceContentHash(string xml)
    {
        var normalized = xml.Replace("\r\n", "\n").Replace("\r", "\n");
        using var sha = SHA256.Create();
        return Convert.ToHexString(sha.ComputeHash(Encoding.UTF8.GetBytes(normalized))).ToLowerInvariant();
    }

    /// <summary>
    /// Most frequent lb `ed` attribute in the body, or null when no lb carries one
    /// (mirrors detectPrimaryEdition). Ties resolve to the FIRST edition to reach the
    /// max count, matching the JS Map-iteration order (insertion order).
    /// </summary>
    public static string? DetectPrimaryEdition(string body)
    {
        var counts = new Dictionary<string, int>();
        var order = new List<string>();
        foreach (Match m in LbEdRe.Matches(body))
        {
            var ed = m.Groups[1].Value;
            if (!counts.ContainsKey(ed)) order.Add(ed);
            counts[ed] = counts.TryGetValue(ed, out var c) ? c + 1 : 1;
        }
        string? best = null;
        int bestN = 0;
        foreach (var ed in order)
        {
            if (counts[ed] > bestN) { best = ed; bestN = counts[ed]; }
        }
        return best;
    }

    private static bool LbEditionAccepted(string tag, string? primaryEd)
    {
        var edMatch = EdAttrRe.Match(tag);
        if (!edMatch.Success) return true;   // no ed → accept
        if (primaryEd == null) return true;  // file has no ed attrs anywhere → accept all
        return edMatch.Groups[1].Value == primaryEd;
    }

    private static List<Token> Tokenize(string body)
    {
        var tokens = new List<Token>();
        int lastIdx = 0;
        foreach (Match m in TagRe.Matches(body))
        {
            if (m.Index > lastIdx)
                tokens.Add(new Token(false, body.Substring(lastIdx, m.Index - lastIdx)));
            tokens.Add(new Token(true, m.Value));
            lastIdx = m.Index + m.Length;
        }
        if (lastIdx < body.Length)
            tokens.Add(new Token(false, body.Substring(lastIdx)));
        return tokens;
    }

    private static string CleanSegmentText(string raw) => WsRunRe.Replace(raw, " ").Trim();

    /// <summary>Port of extractSegments — one segment per outermost p/cell/item or lg.</summary>
    public static List<StructuralSegment> ExtractSegments(string xml)
    {
        var segments = new List<StructuralSegment>();

        var bodyMatch = BodyRe.Match(xml);
        if (!bodyMatch.Success) return segments;
        var body = bodyMatch.Groups[1].Value;
        var primaryEd = DetectPrimaryEdition(body);

        var tokens = Tokenize(body);

        int pDepth = 0;
        bool inLg = false, inHead = false;
        int noteAppDepth = 0;
        int headDepth = 0;
        var currentLbs = new List<string>();
        var currentText = new StringBuilder();
        string currentXmlId = "";
        string currentType = "prose";

        void FlushSegment()
        {
            var cleanText = CleanSegmentText(currentText.ToString());
            if (currentLbs.Count == 0 && cleanText.Length == 0) return;

            segments.Add(new StructuralSegment(new List<string>(currentLbs), cleanText, currentType, currentXmlId));
            currentLbs.Clear();
            currentText.Clear();
            currentXmlId = "";
            currentType = "prose";
        }

        foreach (var tok in tokens)
        {
            if (tok.IsTag)
            {
                var tag = tok.Value;

                // <head> skip (unanchored contains-test, same as the JS /<head[\s>]/)
                if (HeadOpenRe.IsMatch(tag) && !tag.StartsWith("</", StringComparison.Ordinal))
                {
                    inHead = true;
                    headDepth = 1;
                    continue;
                }
                if (inHead)
                {
                    if (HeadOpenRe.IsMatch(tag) && !tag.StartsWith("</", StringComparison.Ordinal)) headDepth++;
                    if (HeadCloseRe.IsMatch(tag))
                    {
                        headDepth--;
                        if (headDepth <= 0) inHead = false;
                    }
                    continue;
                }

                // <note>/<app> content suppression
                if (NoteAppOpenRe.IsMatch(tag) && !tag.StartsWith("</", StringComparison.Ordinal))
                {
                    if (!SelfClosingRe.IsMatch(tag)) noteAppDepth++;
                    continue;
                }
                if (NoteAppCloseRe.IsMatch(tag))
                {
                    noteAppDepth = Math.Max(0, noteAppDepth - 1);
                    continue;
                }

                // container open (p/cell/item)
                if (ContainerOpenRe.IsMatch(tag) && !tag.StartsWith("</", StringComparison.Ordinal))
                {
                    if (pDepth == 0)
                    {
                        var savedLbs = new List<string>(currentLbs);
                        var savedText = currentText.ToString();
                        currentLbs.Clear();
                        currentText.Clear();
                        bool savedHasText = WsRunRe.Replace(savedText, "").Trim().Length > 0;
                        if (savedHasText)
                        {
                            currentLbs.AddRange(savedLbs);
                            currentText.Append(savedText);
                            FlushSegment();
                        }
                        currentLbs.Clear();
                        if (savedLbs.Count > 0 && !savedHasText)
                            currentLbs.AddRange(savedLbs);
                        currentText.Clear();
                        var idMatch = XmlIdAttrRe.Match(tag);
                        currentXmlId = idMatch.Success ? idMatch.Groups[1].Value : "";
                        currentType = "prose";
                    }
                    pDepth++;
                    continue;
                }
                // container close
                if (ContainerCloseRe.IsMatch(tag))
                {
                    pDepth = Math.Max(0, pDepth - 1);
                    if (pDepth == 0) FlushSegment();
                    continue;
                }

                // <lg>
                if (LgOpenRe.IsMatch(tag) && !tag.StartsWith("</", StringComparison.Ordinal))
                {
                    FlushSegment();
                    inLg = true;
                    var idMatch = XmlIdAttrRe.Match(tag);
                    currentXmlId = idMatch.Success ? idMatch.Groups[1].Value : "";
                    currentType = "verse";
                    continue;
                }
                if (LgCloseRe.IsMatch(tag))
                {
                    FlushSegment();
                    inLg = false;
                    continue;
                }

                // <lb>
                if (LbRe.IsMatch(tag))
                {
                    if (noteAppDepth == 0)
                    {
                        var nMatch = NAttrRe.Match(tag);
                        if (nMatch.Success && LbEditionAccepted(tag, primaryEd))
                            currentLbs.Add(nMatch.Groups[1].Value);
                    }
                    continue;
                }

                // structural/metadata skips
                if (SkipOpenRe.IsMatch(tag)) continue;
                if (SkipCloseRe.IsMatch(tag)) continue;

                // <caesura/>
                if (CaesuraRe.IsMatch(tag))
                {
                    if ((pDepth > 0 || inLg) && noteAppDepth == 0) currentText.Append('　');
                    continue;
                }

                // other tags: text flows
            }
            else
            {
                if (inHead) continue;
                if (noteAppDepth > 0) continue;
                if (pDepth > 0 || inLg)
                    currentText.Append(tok.Value);
            }
        }
        FlushSegment();

        // dialogue/commentary detection (same order/regexes as the JS)
        for (int i = 0; i < segments.Count; i++)
        {
            var seg = segments[i];
            if (seg.Type == "verse") continue;

            var type = seg.Type;
            if (DialogueMarkersRe.IsMatch(seg.Text) && SpeakerMarkersRe.IsMatch(seg.Text))
                type = "dialogue";
            if (WumenRe.IsMatch(seg.Text) || ShiSaysRe.IsMatch(seg.Text.TrimStart()))
            {
                if (seg.Text.StartsWith("無門曰", StringComparison.Ordinal))
                    type = "commentary";
            }
            if (type != seg.Type)
                segments[i] = seg with { Type = type };
        }

        return segments;
    }

    /// <summary>Port of buildLbTextMap — lb n-value → accumulated text.</summary>
    public static Dictionary<string, string> BuildLbTextMap(string xml)
    {
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        var bodyMatch = BodyRe.Match(xml);
        if (!bodyMatch.Success) return map;
        var body = bodyMatch.Groups[1].Value;
        var primaryEd = DetectPrimaryEdition(body);

        var tokens = Tokenize(body);

        string? currentLb = null;
        bool inHead = false;
        int headDepth = 0;
        int noteAppDepth = 0;

        foreach (var tok in tokens)
        {
            if (tok.IsTag)
            {
                var tag = tok.Value;
                if (HeadOpenRe.IsMatch(tag) && !tag.StartsWith("</", StringComparison.Ordinal))
                {
                    inHead = true; headDepth = 1; continue;
                }
                if (inHead)
                {
                    if (HeadOpenRe.IsMatch(tag) && !tag.StartsWith("</", StringComparison.Ordinal)) headDepth++;
                    if (HeadCloseRe.IsMatch(tag)) { headDepth--; if (headDepth <= 0) inHead = false; }
                    continue;
                }
                if (NoteAppOpenRe.IsMatch(tag) && !tag.StartsWith("</", StringComparison.Ordinal))
                {
                    if (!SelfClosingRe.IsMatch(tag)) noteAppDepth++;
                    continue;
                }
                if (NoteAppCloseRe.IsMatch(tag))
                {
                    noteAppDepth = Math.Max(0, noteAppDepth - 1);
                    continue;
                }
                if (LbRe.IsMatch(tag))
                {
                    if (noteAppDepth == 0)
                    {
                        var nMatch = NAttrRe.Match(tag);
                        if (nMatch.Success && LbEditionAccepted(tag, primaryEd))
                            currentLb = nMatch.Groups[1].Value;
                    }
                }
            }
            else
            {
                if (inHead) continue;
                if (noteAppDepth > 0) continue;
                if (currentLb != null)
                {
                    var text = CleanSegmentText(tok.Value);
                    if (text.Length > 0)
                    {
                        map[currentLb] = map.TryGetValue(currentLb, out var prev) && prev.Length > 0
                            ? prev + " " + text
                            : text;
                    }
                }
            }
        }
        return map;
    }

    /// <summary>
    /// Port of processFile minus the disk I/O: builds the complete .segments.jsonl
    /// CONTENT (header line + one JSON line per segment + trailing LF) for a
    /// source/translation pair. Byte-identical to the JS generator's file output.
    /// </summary>
    public static string BuildJsonl(string workId, string sourceXml, string transXml)
    {
        var zhSegments = ExtractSegments(sourceXml);
        var enLbMap = BuildLbTextMap(transXml);

        var sb = new StringBuilder();
        sb.Append("{\"source_sha256\":\"").Append(SourceContentHash(sourceXml)).Append("\",\"schema\":\"seg-v1\"}\n");

        int segIdx = 0;
        foreach (var seg in zhSegments)
        {
            segIdx++;
            var unitId = $"{workId}_{segIdx.ToString().PadLeft(3, '0')}";

            var enParts = new List<string>();
            foreach (var lb in seg.LbIds)
            {
                if (enLbMap.TryGetValue(lb, out var enText) && enText.Length > 0)
                    enParts.Add(enText);
            }
            var textEn = string.Join(" ", enParts).Trim();

            // Same key order + JS-style escaping as JSON.stringify in the generator.
            sb.Append("{\"unit_id\":\"").Append(JsEscape(unitId)).Append("\",\"lb_range\":[");
            for (int i = 0; i < seg.LbIds.Count; i++)
            {
                if (i > 0) sb.Append(',');
                sb.Append('"').Append(JsEscape(seg.LbIds[i])).Append('"');
            }
            sb.Append("],\"text_zh\":\"").Append(JsEscape(seg.Text))
              .Append("\",\"text_en\":\"").Append(JsEscape(textEn))
              .Append("\",\"type\":\"").Append(JsEscape(seg.Type))
              .Append("\",\"confidence\":1}\n");
        }

        return sb.ToString();
    }

    /// <summary>
    /// JSON string escaping with JSON.stringify semantics: only `"` `\` and control
    /// chars are escaped (CJK passes through raw, unlike System.Text.Json's default).
    /// </summary>
    internal static string JsEscape(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var ch in s)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\b': sb.Append("\\b"); break;
                case '\f': sb.Append("\\f"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (ch < 0x20)
                        sb.Append("\\u").Append(((int)ch).ToString("x4"));
                    else
                        sb.Append(ch);
                    break;
            }
        }
        return sb.ToString();
    }
}
